#!/bin/bash
# =============================================================================
# 20-databases.sh — install MariaDB 12.x LTS + PostgreSQL 16
#   - both bind to 127.0.0.1 only
#   - root auth via unix_socket / peer (no passwords for admin)
#   - tuned to ~25% RAM for buffer pool / shared_buffers
#   - default test DB dropped on MariaDB
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck disable=SC1091
source "${REPO_DIR}/lib/common.sh"

require_root
load_config

INSTALL_MARIADB="${INSTALL_MARIADB:-yes}"
INSTALL_POSTGRES="${INSTALL_POSTGRES:-yes}"

if [[ "${INSTALL_MARIADB}" != "yes" && "${INSTALL_POSTGRES}" != "yes" ]]; then
    info "Neither MariaDB nor PostgreSQL selected — skipping 20-databases."
    exit 0
fi

MARIADB_VERSION="${MARIADB_VERSION:-12.0}"
PG_VERSION="${PG_VERSION:-16}"

RAM_MB=$(ram_mb)
SHARED_25=$((RAM_MB / 4))
EFFECTIVE_50=$((RAM_MB / 2))
[[ ${SHARED_25} -lt 128 ]] && SHARED_25=128
[[ ${EFFECTIVE_50} -lt 256 ]] && EFFECTIVE_50=256

info "Detected RAM: ${RAM_MB}MB → tuning to shared=${SHARED_25}MB, effective=${EFFECTIVE_50}MB"

# -----------------------------------------------------------------------------
# 1. MariaDB
# -----------------------------------------------------------------------------
if [[ "${INSTALL_MARIADB}" == "yes" ]]; then
    if rpm -q MariaDB-server >/dev/null 2>&1 || rpm -q mariadb-server >/dev/null 2>&1; then
        info "MariaDB already installed."
    else
        info "Installing MariaDB ${MARIADB_VERSION}..."
        curl -fsSL https://downloads.mariadb.com/MariaDB/mariadb_repo_setup -o /tmp/mariadb_repo_setup
        chmod +x /tmp/mariadb_repo_setup
        if ! /tmp/mariadb_repo_setup --mariadb-server-version="mariadb-${MARIADB_VERSION}" 2>/dev/null; then
            warn "MariaDB version ${MARIADB_VERSION} unavailable; falling back to repo default."
            /tmp/mariadb_repo_setup
        fi
        rm -f /tmp/mariadb_repo_setup
        dnf -y install MariaDB-server MariaDB-client
    fi

    info "Writing MariaDB tuning config..."
    mkdir -p /etc/my.cnf.d
    cat > /etc/my.cnf.d/serverdeploy.cnf <<EOF
# Generated by serverdeploy 20-databases.sh
[mariadb]
innodb_buffer_pool_size = ${SHARED_25}M
innodb_log_file_size = 256M
innodb_flush_method = O_DIRECT
innodb_flush_log_at_trx_commit = 1
max_connections = 200
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
skip-name-resolve
bind-address = 127.0.0.1

[client]
default-character-set = utf8mb4
EOF

    systemctl enable mariadb
    systemctl restart mariadb
    sleep 2

    info "Securing MariaDB (drop test db, anonymous users, remote root)..."
    mariadb <<'SQL' || die "MariaDB SQL failed."
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.global_priv WHERE User='' OR User IS NULL;
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
SQL
    success "MariaDB installed and secured."
else
    info "Skipping MariaDB (INSTALL_MARIADB=${INSTALL_MARIADB})."
fi

# -----------------------------------------------------------------------------
# 2. PostgreSQL
# -----------------------------------------------------------------------------
if [[ "${INSTALL_POSTGRES}" == "yes" ]]; then
    if rpm -q "postgresql${PG_VERSION}-server" >/dev/null 2>&1; then
        info "PostgreSQL ${PG_VERSION} already installed."
    else
        info "Installing PostgreSQL ${PG_VERSION}..."
        dnf -y install "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        dnf -qy module disable postgresql || true
        dnf -y install "postgresql${PG_VERSION}-server" "postgresql${PG_VERSION}-contrib"
    fi

    PG_DATA="/var/lib/pgsql/${PG_VERSION}/data"
    if [[ ! -f "${PG_DATA}/PG_VERSION" ]]; then
        info "Initializing Postgres data directory..."
        "/usr/pgsql-${PG_VERSION}/bin/postgresql-${PG_VERSION}-setup" initdb
    fi

    info "Tuning PostgreSQL..."
    PG_CONF="${PG_DATA}/postgresql.conf"
    PG_TUNING_DIR="${PG_DATA}/conf.d"
    PG_TUNING_FILE="${PG_TUNING_DIR}/serverdeploy.conf"
    mkdir -p "${PG_TUNING_DIR}"
    cat > "${PG_TUNING_FILE}" <<EOF
# Generated by serverdeploy 20-databases.sh
listen_addresses = '127.0.0.1'
max_connections = 200
shared_buffers = ${SHARED_25}MB
effective_cache_size = ${EFFECTIVE_50}MB
work_mem = 16MB
maintenance_work_mem = 128MB
wal_compression = on
log_min_duration_statement = 1000
log_line_prefix = '%t [%p] %u@%d '
EOF
    chown postgres:postgres "${PG_TUNING_FILE}"
    chown -R postgres:postgres "${PG_TUNING_DIR}"

    if ! grep -q "include_dir = 'conf.d'" "${PG_CONF}"; then
        echo "" >> "${PG_CONF}"
        echo "include_dir = 'conf.d'" >> "${PG_CONF}"
    fi

    systemctl enable "postgresql-${PG_VERSION}"
    systemctl restart "postgresql-${PG_VERSION}"
    sleep 2
    sudo -u postgres psql -tAc "SELECT version()" >/dev/null || die "Postgres not responding."
    success "PostgreSQL ${PG_VERSION} installed and tuned."
else
    info "Skipping PostgreSQL (INSTALL_POSTGRES=${INSTALL_POSTGRES})."
fi

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------
echo
success "20-databases.sh complete."
[[ "${INSTALL_MARIADB}"  == "yes" ]] && info "  MariaDB  : connect with 'mariadb' (unix_socket auth as root)"
[[ "${INSTALL_POSTGRES}" == "yes" ]] && info "  Postgres : connect with 'sudo -u postgres psql' (peer auth)"
info "  RAM-tuned: shared/buffer=${SHARED_25}MB  effective=${EFFECTIVE_50}MB"
info "  Installed engines bind 127.0.0.1 only — not reachable from network."
